site: Frédérique Lodola - Chasseur Immobilier à Avignon

url: https://chasseurimmobilieravignon.com
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name/
  posts:
    output: true
    permalink: /blog/:slug/
    type: "post"
  testimonials:
    output: true
    permalink: /temoignages-clients/:slug/
    type: "testimonial"
  faqs:
    output: true
    permalink: /faq/:slug/
    type: "faq"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "testimonial" 
  -
    scope:
      path: ""
      type: "faqs"
    values:
      layout: "faq" 

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  #- jekyll-redirect-from

paginate: 6
paginate_path: "/blog/page:num/"

exclude:
  - blog
  - blog/
  - features