site: Frédérique Lodola - Chasseur Immobilier à Avignon

url: https://argon.jekyllthemes.io
baseurl: 

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
    type: "post"
  testimonials:
    output: true
    permalink: /temoignages-clients/:slug
    type: "testimonial"

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post" 
  -
    scope:
      path: ""
      type: "testimonials"
    values:
      layout: "post" 

sass:
  sass_dir: assets/styles
  style: compressed
  sourcemap: never

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"

exclude:
  - blog
  - blog/
  - features